name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install eel python-pptx pyinstaller setuptools
        
    - name: Build EXE with Eel
      run: |
        python -m eel main.py . --onefile --noconsole --name "clickMeToRun"

    - name: Prepare Release Package
      run: |
        mkdir release
        copy dist\clickMeToRun.exe release\
        copy *.pptx release\

    - name: Upload Windows Package
      uses: actions/upload-artifact@v4
      with:
        name: servicePPTgenerator_windows
        path: release/